### ISSUE TITLE
error

### ISSUE THREAD

**Issue by igsbma** [alexcritschristoph/CircMG#2]
Got this error even after I installed required tools, any advice? thanks!

[1] Predicting genes and proteins with Prodigal (this could take a while)...
[2] Generating features for machine learning...
[3] Loading classifier into memory...
/Library/Python/2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version pre-0.18 when using version 0.18. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "./classify.py", line 88, in <module>
    forest_fit = pickle.load( open( "./data/classifier.p", "rb" ) )
  File "sklearn/tree/_tree.pyx", line 633, in sklearn.tree._tree.Tree.__setstate__ (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-EIz_8i-build/sklearn/tree/_tree.c:7860)
KeyError: 'max_depth'

**Comment by alexcritschristoph** [comment]
This should be fixed with the latest updates. Let me know if you have any other issues or requests!
Alex
